---
- hosts: localhost
  become: yes
  gather_facts: False
  tasks:

  - name: Install EPEL-release
    yum: name=epel-release state=present
    
  - name: check if myvolume exists in nginx server
    command: docker run -d -p 8088:80 --name=nginxtest --mount source=/var/lib/jenkins/workspace/jenkins-doc-image/index.html,destination=/usr/share/nginx/html nginx:latest
