---
- hosts: localhostengine-nginx
  become: yes
  gather_facts: False
  tasks:

  - name: Install EPEL-release
    yum: name=epel-release state=present
    
  #- name: check if myvolume exists in nginx server
   # command: docker cp /var/lib/jenkins/workspace/jenkins-doc-image/index.html f4cebe04268c861d719c732504fb73e9101b00ba999829faeda42461ea9601a3:/usr/share/nginx/html
 # - name: Download latest file
  #  get_url: url=http://{{nexusip}}:8081/nexus/content/repositories/JEN-DOCKER/{{groupid}}/{{time}}/{{build}}/{{version}} dest=/tmp/ mode=755
  
 # - name: download file
  #  command: wget  http://192.168.1.95:8081/nexus/content/repositories/JEN-DOCKER/doc/{{time}}/{{build}}/{{version}} dest=/tmp/
 # - name: remove previous files
  #  command: rm -rf /root/*.html
    
  #- name: remove web dir contents
   # file: path='/tmp/{{ item }}' state=absent
    #with_fileglob:
     #  - /tmp/*.html
     
  - name: remove older html files
    shell: rm -rf /tmp/*.html
  
  - name: download file
    get_url: url=http://192.168.1.95:8081/nexus/content/repositories/JEN-DOCKER/doc/{{time}}/{{build}}/{{version}} dest=/tmp/

  - name: rename the downloaded file
    shell: mv /tmp/*.html /tmp/index.html
  
  - name: copy file
    command: docker cp /tmp/index.html 369494335ce0313af1e1d6bfbc921a9af000fc5cccd784f4714db4f8a55d52e5:/usr/share/nginx/html
    
  - name: Log into DockerHub
    docker_login:
      username: saikiran786
      ### {{password-docker-hub}} ###
      password: 9966786786
      email: saikiran786786@gmail.com
      
  - name: Stop a container
    docker_container:
      name: jen-docker-nginx
      state: stopped
      
  - name: committing the modified container
    ### {{new-repo-name}} ###
    command: docker commit jen-docker-nginx {{new_repo_name}}
    
  - name: now pushing the modified image to the docker hub repository
    ###  {{new-repo-to-push}} ###
    command: docker push {{new_repo_to_push}}
